---
- name: Installation de l'environnement Minecraft sur VM GCP
  hosts: all
  become: true
  vars:
    minecraft_version: "1.20.4"  # Version de Minecraft à installer
    java_package: "openjdk-21-jre-headless"  # Paquet Java à installer

  tasks:
    - name: Mise à jour du cache APT
      apt:
        update_cache: yes  # Met à jour le cache APT

    # Installation de Java 21
    - name: Télécharger Java 21
      get_url:
        url: "https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb"
        dest: "/tmp/jdk-21_linux-x64_bin.deb"
    - name: Installer Java 21
      apt:
        deb: "/tmp/jdk-21_linux-x64_bin.deb"

    - name: Ajouter la clé GPG du dépôt Google Cloud SDK
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg  # URL de la clé GPG
        state: present

    - name: Téléchargement de Minecraft Server JAR
      get_url:
        url: "https://piston-data.mojang.com/v1/objects/4707d00eb834b446575d89a61a11b5d548d8c001/server.jar"  # URL du fichier JAR du serveur Minecraft
        dest: /opt/server.jar  # Destination du fichier téléchargé

    - name: Creation du service Minecraft dans linux
      copy:
        dest: /etc/systemd/system/minecraft.service  # Chemin du fichier de service systemd
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=minecraft
          WorkingDirectory=/opt
          ExecStart=java -Xmx1024M -Xms1024M -jar /opt/server.jar nogui
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Relancer le daemon systemd
      systemd:
        daemon_reload: yes  # Recharge le daemon systemd pour prendre en compte le nouveau service

    - name: Installation de UFW
      apt:
        name: ufw  # Installe le pare-feu UFW
        state: present

    - name: Ouvrir les ports dans UFW
      ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
        direction: in
      with_items:
        - { port: "25565", proto: "tcp" }
        - { port: "22", proto: "tcp" }

    - name: Activer UFW
      ufw:
        state: enabled  # Active UFW

    - name: Créer l'utilisateur minecraft
      user:
        name: minecraft  # Crée un utilisateur système pour Minecraft
        system: yes
        create_home: no
        shell: /bin/false

    # attribuer les droits sur /opt
    - name: Attribuer les droits sur le dossier /opt/
      file:
        path: /opt/
        owner: minecraft
        group: minecraft
        mode: '0755'

    - name: Accepter l'EULA de Minecraft
      copy:
        dest: /opt/eula.txt  # Crée le fichier eula.txt pour accepter l'EULA
        content: "eula=true"
        owner: minecraft
        group: minecraft
        mode: '0644'

    - name: Créer le fichier server.properties
      copy:
        dest: /opt/server.properties  # Chemin du fichier server.properties
        content: |
          server-port=25565
          server-ip=
          max-players=5
          online-mode=true
          motd=A Minecraft Server
        owner: minecraft
        group: minecraft
        mode: '0644'

    - name: Active et démarre le service Minecraft 
      systemd:
        name: minecraft  # Active et démarre le service Minecraft
        enabled: yes
        state: started
        